### PR TITLE
Update test-file.html

### PR DESCRIPTION
**Pull request by nickdiaconou**
This is my suggestion for what to do on Quine questing testing.

### CODE REVIEW

**Comment by nickdiaconou** [comment]
@quest-bot loot

**Comment by nickdiaconou** [comment]
@quest-bot stash 100

**Comment by bigfishronald** [comment]
@quest-bot stash 100

**Comment by nickdiaconou** [comment]
@quest-bot loot

**Comment by nickdiaconou** [comment]
@quest-bot loot #1

**Review by bigfishronald — DISMISSED** [review]
Please can you change the title in the html doc to reference the relevant issue?

**Comment by nickdiaconou** [comment]
@quest-bot reward #1

**Pull request merged**
